### ISSUE TITLE
DOIs not loaded

### ISSUE THREAD

**Issue by ctgraham** [jonasraoni/article-importer-plugin#12]
The use of PubId plugins (such as for DOIs) requires loading the plugin before referencing the associated `$publication->setData()` call.

As such, calls here:
https://github.com/jonasraoni/article-importer-plugin/blob/bf6fb9159131cdaedb71a40bc01aae9f00e02445/parsers/jats/PublicationParser.inc.php#L107
and here:
https://github.com/jonasraoni/article-importer-plugin/blob/bf6fb9159131cdaedb71a40bc01aae9f00e02445/parsers/aPlusPlus/PublicationParser.inc.php#L98
will silently fail for `$type` values other than "publisher-id".

**Comment by jonasraoni** [comment]
Hmm, I already know this issue must be happening in other places 👀
