### ISSUE TITLE
Setting a surname to blank sets a blank surname

### ISSUE THREAD

**Issue by ctgraham** [jonasraoni/article-importer-plugin#19]
https://github.com/jonasraoni/article-importer-plugin/blob/98bc18ca6d07410bd3cdac6d69565fc183376a8a/parsers/jats/AuthorParser.inc.php#L75

Setting the value of `$lastName` as `''` actually creates a 'surname' data element in the `author_settings` table, which then creates unwanted effects of (for example) setting a blank surname in the CrossRef export.

Obviously this raised data integrity questions for the product itself; but, for now, I think conditionally setting this property should be preferred.
```
if ($lastName) {
  $author->setData('familyName', $lastName, $this->getLocale());
}
```

**Comment by ctgraham** [comment]
Or maybe `$lastName = null;` would work here?
https://github.com/jonasraoni/article-importer-plugin/blob/98bc18ca6d07410bd3cdac6d69565fc183376a8a/parsers/jats/AuthorParser.inc.php#L52

But I think we still might have blank surnames in the data.

**Comment by jonasraoni** [comment]
I'd say using `null` must be safe, but without testing/digging further, who knows :)
Anyway, it's better to check everything before assigning values/calling functions that might have side-effects.

ps: The `selectText()` is making use of `strip_tags()` + `trim()`.
