### ISSUE TITLE
Cannot insert DateTime format into MariaDB

### ISSUE THREAD

**Issue by ewhanson** [jonasraoni/article-importer-plugin#20]
Hi @jonasraoni,

I was running a test import with this plugin and got a fatal error whenever an insert statement include a prepared date format (e.g. `$publicationDate->format(\DateTime::RFC3339)`). I had to use the `Y-m-d H:i:s` format rather than one of the `DateTime` constants to successfully insert the a formatted date into a `DATETIME` column in MariaDB. 

Is this an issue you've come across before? I'm happy to submit a PR.

Thanks!

**Comment by jonasraoni** [comment]
Hi!
So far I've just imported submissions using MySQL, so feel free to send a PR.
I'd like to [refactor](https://github.com/jonasraoni/article-importer-plugin/issues/11) this plugin, but that's not going to happen unless its usage increases. Also, there's another [issue](https://github.com/jonasraoni/article-importer-plugin/issues/19) that needs to be validated :)

**Comment by ewhanson** [comment]
Thanks @jonasraoni! I created a PR that adjusted the date time format used for inserts to the database. 

PR: #21
