### ISSUE TITLE
Update for OJS 3.3 compatibility

### ISSUE THREAD

**Issue by ewhanson** [jonasraoni/article-importer-plugin#22]
The current version is incompatible with OJS 3.3 and the changes made to how submission files are handled.

@jonasraoni, I'm working on this now and will make a PR once its ready!

**Comment by jonasraoni** [comment]
Thanks!

Ideally this plugin should be updated to use the OJS API to decrease the friction, but I guess it's not capable of storing all the information we need yet. As a general solution it could just produce XML documents for the Native XML plugin (I didn't know about its existence when I wrote this), but it will probably require a huge refactoring 😭

**Comment by ewhanson** [comment]
Hey @jonasraoni, I've created a PR to add OJS 3.3 compatibility. Have a look and let me know what you think!

PR: #23

**Comment by jonasraoni** [comment]
Sorry for the delay, I merged =]
