### ISSUE TITLE
Authors not persisted to publication

### ISSUE THREAD

**Issue by ctgraham** [jonasraoni/article-importer-plugin#5]
Running the import appeared to assign authors without an associated publication.

The association is intended here:
https://github.com/jonasraoni/article-importer-plugin/blob/9a8d404b29e1142c7ce8d1800719ec3746bf4a17/parsers/jats/AuthorParser.inc.php#L74
and here:
https://github.com/jonasraoni/article-importer-plugin/blob/9a8d404b29e1142c7ce8d1800719ec3746bf4a17/parsers/aPlusPlus/AuthorParser.inc.php#L71

But the publication passed in to this function has not yet been persisted to the database, and has no id.
https://github.com/jonasraoni/article-importer-plugin/blob/9a8d404b29e1142c7ce8d1800719ec3746bf4a17/parsers/jats/PublicationParser.inc.php#L116-L119
and:
https://github.com/jonasraoni/article-importer-plugin/blob/9a8d404b29e1142c7ce8d1800719ec3746bf4a17/parsers/aPlusPlus/PublicationParser.inc.php#L107-L110

**Comment by jonasraoni** [comment]
Yeah, good catch! In general, I think this issue should have raised an exception in the PKP code (as long as it's a required field).
Also, I'd like to be able to reuse authors somehow to save some space and keep data linked.
