### ISSUE TITLE
Enhancement: capture original XML as a submission file

### ISSUE THREAD

**Issue by ctgraham** [jonasraoni/article-importer-plugin#7]
For permanency of the original imported XML file, we can capture it as a submission file.

In the case of JATS, there might be value to publishing it (and dependent files) as a Galley.

**Comment by jonasraoni** [comment]
Yeah! I remember we had some extra files linked, such as videos, which were discarded (probably inserted manually later on, since there were few).
I consider this as a requirement, but I'm not sure when I'll be able to drop some time here.

**Comment by ctgraham** [comment]
I'll be adding support for this soon.
